# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-3.10

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
    - libmpd-0.9.0.4
    - uuid-aeson-0.1.0.0
    - xdg-basedir-0.2.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
